apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  config.hjson: |-
    {
      setup: {
        admin_username: "admin"
        admin_password: "password"
        site_name: "Lemmy Help"
      }
        hostname: "lemmy.example.com"
        bind: "0.0.0.0"
        port: 8536
        tls_enabled: true
      pictrs: {
        url: "http://pictrs-service.pictrs.svc.cluster.local:8080/"
        api_key: ""
      }
        database: {
        database: "lemmy"
        user: "lemmy"
        password: "lemmy-password"
        host: "postgres-service-p.postgres.svc.cluster.local"
        port: 5432
        pool_size: 5
      }
    }